# Generated by Django 5.2.12 on 2026-04-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='User',
            new_name='user',
        ),
    ]
